Github actions build system has been added
SoftFx/TTAlgo pull request #1
Opened 2023-03-28 14:28 UTC by AndrewKhloptsau

2023-03-28 16:01 UTC, pkindruk requested changes
A few more changes to workflow file:
1. Rename `algo-studio-build.yml` -> `build-release.yml`
2. Change workflow name to `TTAlgo Release`
3. Change run name to `TTAlgo ${{ inputs.releaseVersion }}`3
4. Change artifact name to `TTAlgo Release`
5. Change tag name to `release-v${{ inputs.releaseVersion }}`

2023-03-28 16:01 UTC, pkindruk commented on build.cake
> +         var configuratorInstallPath = serverBinPath.Combine("Configurator");
Configurator binaries should be copied to `serverBinPath`, because installer relies on them

2023-03-29 07:53 UTC, AndrewKhloptsau commented on build.cake
> +         var configuratorInstallPath = serverBinPath.Combine("Configurator");
Done

2023-03-29 09:27 UTC, pkindruk approved these changes

2023-03-29 09:29 UTC, merged